### PR TITLE
Add CallbackQuery with game_short_name can be processed

### PR DESCRIPTION
**Pull request by dammer**
Hi!
 I was testing tourmaline for a possible replacement for my telegram api client and I really liked it. 
But the key functionality for me is the game callback answer unfortunately not implemented.

```crystal
require "tourmaline"
GAME_NAME = "my_game_name"

class TelegramBot < Tourmaline::Client
  @[OnCallbackQuery(GAME_NAME)]
  def process_query(ctx)
    game = ActiveGame.process_update(ctx.query)
    answer_callback_query(ctx.query.id, url: game.player_a_route.url)
  end
end
```
So the game callback is handled fine in my app.
Thanks you.

### CODE REVIEW

**Comment by watzon** [comment]
I don't know much about the `game_short_name` property since I haven't done much of anything with games. Would it ever be supplied along with `data`, or would it generally be an either-or thing?

**Comment by dammer** [comment]
As described [callbackquer](https://core.telegram.org/bots/api#callbackquer) Exactly one of the fields data or game_short_name will be present.

**Comment by watzon** [comment]
Right. Thanks for this!

**Comment by dammer** [comment]
Excellent, Thank you!

if it comes in handy for the documentation, I made a  [gist](https://gist.github.com/dammer/fa0e0aa388bc75962ea6f59a2dc75959) how to just add an HTTP::Handler for Tourmaline bot in to Lucky.

**Pull request merged**
